{
  imports = [
    ./binds
    ./ccc
    ./diffview
    ./direnv
    ./freeze
    ./fzf-lua
    ./gestures
    ./harpoon
    ./icon-picker
    ./images
    ./lean
    ./leetcode-nvim
    ./mkdir
    ./motion
    ./multicursors
    ./new-file-template
    ./nix-develop
    ./nvim-biscuits
    ./oil-nvim
    ./outline
    ./preview
    ./qmk-nvim
    ./sleuth
    ./smart-splits
    ./snacks-nvim
    ./surround
    ./targets-vim
    ./telescope
    ./wakatime
    ./yanky-nvim
    ./yazi-nvim
    ./undotree
    ./zen-mode
  ];
}
